### ISSUE TITLE
Multiline maps are not parsed

### ISSUE THREAD

**Issue by joneff** [mleg/sass-variable-parser#4]
* **I'm submitting a ...**
[x] bug report

* **Summary**

When parsing multiline maps, like the one below, I get `unclosed parenthesis` error:

```scss
$map: (
    key1: val
) !default;
```

Stack trace:

```
[17:23:53] Error: unclosed parenthesis
    at Object.module.exports.renderSync (D:\work\kendo-themes\node_modules\node-sass\lib\index.js:441:16)
    at Object.renderValuesToCSS [as default] (D:\work\kendo-themes\node_modules\sass-variable-parser\build\main\lib\render-values-to-css.js:35:10)
    at parseVariables (D:\work\kendo-themes\node_modules\sass-variable-parser\build\main\lib\parse-variables.js:50:47)
    at D:\work\kendo-themes\gulpfile.js:130:23
    at taskWrapper (D:\work\kendo-themes\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:402:14)
    at runBound (domain.js:415:12)
    at asyncRunner (D:\work\kendo-themes\node_modules\async-done\index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Seeing the error originates in node-sass, I am assuming that the variables are parsed per line.

**Comment by mleg** [comment]
Sorry, it's unmaintained. Recommend using [CSS modules](https://github.com/mleg/sass-vars-to-js-example) for the same purpose.
